### ISSUE TITLE
Devs. Aonde estão? Aqui estão!

### ISSUE THREAD

**Issue by romeumattos** [PHPSC/meetups#1]
# Palestra: Devs. Aonde estão? Aqui estão!
## Chamada da palestra

Empresas de TI reclamam da falta de profissionais qualificados e esse problema atinge também as jovens startups. Além da dificuldade de criar um novo negocio, montar uma boa equipe de tecnologia é um grande desafio.
Mas os devs estão aqui, eles existem. Talvez não na quantidade desejada, mas temos qualidade e vontade o suficiente para ajudar. Então onde está o problema? Por que as startups tem tanta dificuldade para montar uma boa equipe de tecnologia? 
Nessa palestra faço algumas observações a respeito de cultura interna para criação de um bom time de desenvolvimento dentro de startups. Formas de gestão, construção de carreira, externalização do time e reconhecimento são alguns pontos que podem te ajudar a montar o seu Dream Team.
## Resumo

Baseado em uma jovem vivência faço algumas observações sobre cultura interna para criação de um bom time de desenvolvimento dentro de startups. Formas de gestão, alinhamento, construção de carreira, externalização do time, contribuição com open source, reconhecimento e treinamento são alguns passos.
## Observações

Esta é uma palestra que apresentei no TDC de Floripa (trilha de startups) com duração de 15 minutos, porém pode ser estendida para 25 minutos, pois em 15 ficou bem corrido ou ainda fazer uma discussão sobre o tema com os participantes.
## Quem sou?

Olá! Me chamo Romeu trabalho com desenvolvimento pra web desde 2010 e nos últimos anos me dedico a trabalhar com projetos de impacto positivo na sociedade. Já trabalhei em empresas grandes com grandes projetos, mas atualmente prefiro trabalhar em pequenas empresas que querem ter grades projetos. Gosto bastante do meio de startups e acredito que seja um bom ambiente para experimentar novas tecnologias e pensar no melhor modelo para desenvolver.

**Comment by sergiors** [comment]
Oi @romeumattos tudo bem?

Primeiro, obrigado pela disposição, espero que você seja o primeiro de muitos, precisamos de pessoas assim!

Eu não vejo problema em ter uma palestra de 15min e outras duas de 40min. 

O que acham? \cc @mingomax @mrprompt

**Comment by romeumattos** [comment]
Oi @sergiors. Tudo certo.

Por mim pode ser de 15 minutos. Caso precise estender um pouco também fico a disposição.

:+1:

**Comment by mrprompt** [comment]
@romeumattos @sergiors @mingomax acho legal a idéia, tanto da palestra quanto do tempo. Também podemos deixar qualquer discussão adicional para um Shark Bowl ao final do evento, o que acham? Mas tb achei ótimo a idéia de duas palestras de 40min.
